services:

# DATABASE

  mariadb:
    image: cdeville/mariadb:v1.0.0
    container_name: MyMariadb
    restart: always
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    secrets:
      - db_database
      - db_root_password
      - db_user
      - db_user_password
    environment:
      - CHARSET=${DB_CHARSET}
      - COLLATION=${DB_COLLATION}
      # SECRETS
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_USER_PASSWORD}
    networks:
      - deepest_dream
    volumes:
    - ~/data/srcs_dbdata:/var/lib/mysql

# WEB SERVER

  nginx:
    image: cdeville/nginx:v1.0.0
    container_name: MyNginx
    restart: always
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
      # SECRETS
      - AUTH_USER=${AUTH_USER}
      - AUTH_PASSWORD=${AUTH_PASSWORD}
    depends_on:
      - wordpress
      - adminer
      - hugo
      - goaccess
    networks:
      - deepest_dream
    ports:
      - "443:443"
    volumes:
      - ~/data/srcs_wordpress_volume:/var/www/html
      - ~/data/srcs_nginx_logs:/var/log/nginx
    secrets:
      - certificate
      - key
      - auth_user
      - auth_password

## WORDPRESS

  wordpress:
    image: cdeville/wordpress:v1.0.0
    container_name: MyWordpress
    restart: always
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    environment:
      - WEBSITE_TITLE=${WEBSITE_TITLE}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - CUSTOM_URL=${CUSTOM_URL}
      # SECRETS
      - WORDPRESS_USER=${WORDPRESS_USER}
      - WORDPRESS_PASSWORD=${WORDPRESS_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_USER_PASSWORD=${DB_USER_PASSWORD}
    secrets:
      - wordpress_password
      - wordpress_user
      - db_user
      - db_user_password
      - db_database
    depends_on:
      - redis
      - mariadb
    networks:
      - deepest_dream
    volumes:
      - ~/data/srcs_wordpress_volume:/var/www/html

##### BONUS #####

# ADMINER (DATABASE INTERFACE MANAGER)

  adminer:
    image: cdeville/adminer:v1.0.0
    container_name: MyAdminer
    restart: always
    build:
      context: ./bonus/adminer/
      dockerfile: Dockerfile
    depends_on:
     mariadb:
       condition: service_started
       restart: true
    networks:
      - deepest_dream
    volumes:
      - ~/data/srcs_wordpress_volume:/var/www/html

# FTP SERVER

  vsftpd:
    image: cdeville/vsftpd:v1.0.0
    container_name: MyVsftpd
    restart: always
    build:
      context: ./bonus/vsftpd/
      dockerfile: Dockerfile
    secrets:
      - vsftpd_password
      - vsftpd_user
      - vsftpd.crt
      - vsftpd.key
    environment:
      - PASV_ENABLE=${PASV_ENABLE}
      - PASV_MIN_PORT=${PASV_MIN_PORT}
      - PASV_MAX_PORT=${PASV_MAX_PORT}
      - FTP_MODE=${FTP_MODE}
      - LOG_STDOUT=${LOG_STDOUT}
      # SECRETS
      - VSFTPD_USER=${VSFTPD_USER}
      - VSFTPD_PASSWORD=${VSFTPD_PASSWORD}
    ports:
      - "20-21:20-21"
      # ftp passive ports
      - "${PASV_MIN_PORT:-21100}-${PASV_MAX_PORT:-21110}:${PASV_MIN_PORT:-21100}-${PASV_MAX_PORT:-21110}"
    volumes:
      #- wordpress_volume:/srv/ftps
      - ~/data/srcs_wordpress_volume:/mnt/wordpress

#STATIC WEBPAGE GENERATOR (HUGO)

  hugo:
    image: cdeville/hugo:v1.0.0
    container_name: MyHugo
    restart: always
    build:
      context: ./bonus/hugo/
      dockerfile: Dockerfile
    networks:
      - deepest_dream
    volumes:
      - ~/data/srcs_hugo_volume:/var/hugo

# REDIS FOR DATABSE CACHING ON WORDPRESS

  redis:
    image: cdeville/redis:v1.0.0
    container_name: MyRedis
    restart: always
    build:
      context: ./bonus/redis/
      dockerfile: Dockerfile
    networks:
      - deepest_dream

# GOACCESS FOR MONITORING

  goaccess:
    image: cdeville/goaccess:v1.0.0
    container_name: MyGoaccess
    restart: always
    build:
      context: ./bonus/goaccess/
      dockerfile: Dockerfile
    environment:
      - WEBSOCKET_URL=${WEBSOCKET_URL}
    networks:
      - deepest_dream
    volumes:
      - ~/data/srcs_wordpress_volume:/var/www/html
      - ~/data/srcs_nginx_logs:/var/log/nginx

# NETWORK

networks:
  deepest_dream:
    driver: bridge

# DOCKER SECRETS

secrets:
  certificate:
    file: ../secrets/nginx.crt
  key:
    file: ../secrets/nginx.key
  wordpress_password:
    file: ../secrets/wordpress_password.txt
  wordpress_user:
    file: ../secrets/wordpress_user.txt
  db_database:
    file: ../secrets/db_database.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user:
    file: ../secrets/db_user.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
  vsftpd_password:
    file: ../secrets/vsftpd_password.txt
  vsftpd_user:
    file: ../secrets/vsftpd_user.txt
  auth_user:
    file: ../secrets/auth_user.txt
  auth_password:
    file: ../secrets/auth_password.txt
  vsftpd.crt:
    file: ../secrets/vsftpd.crt
  vsftpd.key:
    file: ../secrets/vsftpd.key
