services:
  mariadb:
    image: cdeville/mariadb:v1.0.0
    container_name: MyMariadb
    restart: always
    build:
      context: ./requirements/mariadb
      dockerfile: Dockerfile
    secrets:
      - db_database
      - db_root_password
      - db_user
      - db_user_password
    networks:
      - deepest_dream
    volumes:
    - ~/data/srcs_dbdata:/var/lib/mysql
  nginx:
    image: cdeville/nginx:v1.0.0
    container_name: MyNginx
    restart: always
    build:
      context: ./requirements/nginx/
      dockerfile: Dockerfile
    environment:
      - DOMAIN_NAME=${DOMAIN_NAME}
    depends_on:
      - wordpress
      - adminer
      - hugo
      - goaccess
    networks:
      - deepest_dream
    ports:
      - "443:443"
    volumes:
      - ~/data/srcs_wordpress_volume:/var/www/html
      - ~/data/srcs_nginx_logs:/var/log/nginx
    secrets:
      - certificate
      - key
      - auth_user
      - auth_password
  wordpress:
    image: cdeville/wordpress:v1.0.0
    container_name: MyWordpress
    restart: always
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    environment:
      - WEBSITE_TITLE=${WEBSITE_TITLE}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - CUSTOM_URL=${CUSTOM_URL}
    secrets:
      - source: wordpress_password
        target: wordpress_password
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: wordpress_user
        target: wordpress_user
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: db_user
        target: db_user
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: db_user_password
        target: db_user_password
        uid: '1000'
        gid: '1000'
        mode: 0440
      - source: db_database
        target: db_database
        uid: '1000'
        gid: '1000'
        mode: 0440
    depends_on:
      - redis
      - mariadb
    networks:
      - deepest_dream
    volumes:
      - ~/data/srcs_wordpress_volume:/var/www/html
##### BONUS #####
  adminer:
    image: cdeville/adminer:v1.0.0
    container_name: MyAdminer
    restart: always
    build:
      context: ./bonus/adminer/
      dockerfile: Dockerfile
    depends_on:
     mariadb:
       condition: service_started
       restart: true
    networks:
      - deepest_dream
    volumes:
      - ~/data/srcs_wordpress_volume:/var/www/html
  vsftpd:
    image: cdeville/vsftpd:v1.0.0
    container_name: MyVsftpd
    restart: always
    build:
      context: ./bonus/vsftpd/
      dockerfile: Dockerfile
    secrets:
      - vsftpd_password
      - vsftpd_user
      - vsftpd.crt
      - vsftpd.key
    ports:
      - "20-21:20-21"
      # ftp passive ports
      - "24100-24110:21100-21110"
    volumes:
      #- wordpress_volume:/srv/ftps
      - ~/data/srcs_wordpress_volume:/mnt/wordpress
  hugo:
    image: cdeville/hugo:v1.0.0
    container_name: MyHugo
    restart: always
    build:
      context: ./bonus/hugo/
      dockerfile: Dockerfile
    networks:
      - deepest_dream
    volumes:
      - ~/data/srcs_hugo_volume:/var/hugo
  redis:
    image: cdeville/redis:v1.0.0
    container_name: MyRedis
    restart: always
    build:
      context: ./bonus/redis/
      dockerfile: Dockerfile
    networks:
      - deepest_dream
  goaccess:
    image: cdeville/goaccess:v1.0.0
    container_name: MyGoaccess
    restart: always
    build:
      context: ./bonus/goaccess/
      dockerfile: Dockerfile
    environment:
      - WEBSOCKET_URL=${WEBSOCKET_URL}
    networks:
      - deepest_dream
    volumes:
      - ~/data/srcs_wordpress_volume:/var/www/html
      - ~/data/srcs_nginx_logs:/var/log/nginx
networks:
  deepest_dream:
    driver: bridge
secrets:
  certificate:
    file: ../secrets/nginx.crt
  key:
    file: ../secrets/nginx.key
  wordpress_password:
    file: ../secrets/wordpress_password.txt
  wordpress_user:
    file: ../secrets/wordpress_user.txt
  db_database:
    file: ../secrets/db_database.txt
  db_root_password:
    file: ../secrets/db_root_password.txt
  db_user:
    file: ../secrets/db_user.txt
  db_user_password:
    file: ../secrets/db_user_password.txt
  vsftpd_password:
    file: ../secrets/vsftpd_password.txt
  vsftpd_user:
    file: ../secrets/vsftpd_user.txt
  auth_user:
    file: ../secrets/auth_user.txt
  auth_password:
    file: ../secrets/auth_password.txt
  vsftpd.crt:
    file: ../secrets/vsftpd.crt
  vsftpd.key:
    file: ../secrets/vsftpd.key
